### ISSUE TITLE
Web application example usable only on Chrome !

### ISSUE THREAD

**Issue by ranadeep47** [soyjavi/tuktuk#24]
The Scroll bars are not working as they should in firefox 18 ! . The web application template rendering in ie 9 and 10 is just not right . Ive attached images . atleast 25% of the visitors use ie 9,10 so thats huge .

![ff18](https://f.cloud.github.com/assets/3015226/628655/8d7daa48-d0de-11e2-81d5-de7936cf8cf5.png)
![ie9](https://f.cloud.github.com/assets/3015226/628656/8d820b4c-d0de-11e2-9fe9-af4d6fc7f6bd.png)
![ie10](https://f.cloud.github.com/assets/3015226/628657/8dbfffec-d0de-11e2-8324-3e34fa3cd98b.png)

**Comment by ranadeep47** [comment]
The flexbox syntax is changed and you might not have updated . im not sure . but have a look at this 
http://css-tricks.com/old-flexbox-and-new-flexbox/
http://css-tricks.com/using-flexbox/

**Comment by RobertinoValue** [comment]
Resizing the width of the browser window down in Chrome doesn't look correct to me either.
I hope this gets fixed soon, because I would like to use this with a Bones theme.

Tuktuk Web App Demo in Desktop Chrome 27.0.1453.110 m :

![Tuktuk Web App Demo in Desktop Chrome 27.0.1453.110 m](http://oi42.tinypic.com/34xm2vm.png)

![Tuktuk Web App Demo in Desktop Chrome 27.0.1453.110 m](http://oi41.tinypic.com/35ipsmt.jpg)

**Comment by soyjavi** [comment]
For webapp in mobile devices use http://lungo.tapquo.com

**Comment by RobertinoValue** [comment]
OK, Thanks. I'll do that tomorrow.
Had a quick look, and it looks cool.
